services:
  redis:
    image: redis:7-alpine
    # container_name: my_redis_broker
    command: "redis-server"
    volumes:
      - redis-data:/data
    ports:
      - "8999:6379"

volumes:
  redis-data: