services:
  redis:
    image: redis:7-alpine
    container_name: test-redis
    command: "redis-server"
    volumes:
      - redis-data:/data
    ports:
      - "8999:6379"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin_123
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"

volumes:
  redis-data:
  postgres_data: