services:
  redis:
    image: redis:7-alpine
    container_name: test-redis
    command: "redis-server"
    volumes:
      - redis-data:/data
    ports:
      - "8999:6379"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin_123
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: celery_app

    volumes:
      - .:/celery_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: celery -A CeleryApp worker --loglevel=INFO
    volumes:
      - .:/celery_app
    depends_on:
      - web

volumes:
  redis-data:
  postgres_data:
