# Generated by Django 5.2.4 on 2025-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
