# Generated by Django 5.2.4 on 2025-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_testmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='user_id',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
